---
- name: sakumoto hp directory
  file: path="/home/xshsaku/public_html" state=directory owner=xshsaku group=xshsaku mode=0775
  tags: nginx
  sudo: yes

- name: Upload Test File
  copy: src="xshsaku/index.html" dest="/home/xshsaku/public_html/index.html" owner=xshsaku group=xshsaku mode=0644
  tags: nginx
  sudo: yes

- name: Allow HTTP/HTTPS
  ufw: rule=allow port=80
  tags: ufw
  sudo: yes

